# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- data types: b,i,u,f,c,m,M,O,S,u,V
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting

In [1]:
import numpy as np

In [164]:
# !pip install numpy

In [165]:
l1 = [1,2,3,4,5]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]]

In [166]:
n1 = np.array(l1,dtype = 'f')
n2 = np.array(l2)
n3 = np.array(l3)

In [175]:
n1

array([1., 2., 3., 4., 5.], dtype=float32)

In [9]:
n2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
n3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [11]:
type(n1)

numpy.ndarray

In [12]:
n1.shape

(5,)

In [13]:
n2.shape

(3, 2)

In [14]:
n3.shape

(2, 3, 2)

In [15]:
n3.ndim

3

In [16]:
n3[0,1,0]

np.int64(3)

In [17]:
n1[2]

np.int64(3)

In [20]:
n2[1]

array([3, 4])

In [22]:
n3[1,2]

array([50, 60])

In [28]:
for i in l3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
10
20
30
40
50
60


In [29]:
for ele in np.nditer(n3):
    print(ele)

1
2
3
4
5
6
10
20
30
40
50
60


In [33]:
for ind,ele in np.ndenumerate(n3):
    print(ind,'-->',ele)

(0, 0, 0) --> 1
(0, 0, 1) --> 2
(0, 1, 0) --> 3
(0, 1, 1) --> 4
(0, 2, 0) --> 5
(0, 2, 1) --> 6
(1, 0, 0) --> 10
(1, 0, 1) --> 20
(1, 1, 0) --> 30
(1, 1, 1) --> 40
(1, 2, 0) --> 50
(1, 2, 1) --> 60


more creation methods: arange, linspace, ones, zeros, eye, diag

In [55]:
na = np.arange(1,21,2,dtype='int16')

In [56]:
na.dtype

dtype('int16')

In [57]:
na

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int16)

In [61]:
np.linspace(100,200,5)

array([100., 125., 150., 175., 200.])

In [65]:
np.ones((2,3,2),dtype='i')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [66]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [72]:
np.eye(4,dtype = 'i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [73]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [79]:
(np.random.rand(2,3,2)*100)+100

array([[[102.39230654, 126.86058755],
        [140.7357499 , 105.22117261],
        [193.74621991, 127.04319102]],

       [[168.29996811, 138.81254712],
        [131.42716978, 129.6578381 ],
        [179.72505653, 104.59848425]]])

In [76]:
np.random.randint(1000,2000,size=(2,4))

array([[1111, 1383, 1126, 1653],
       [1759, 1913, 1957, 1990]], dtype=int32)

In [77]:
np.random.random((3,4))

array([[0.67823875, 0.35521759, 0.00843601, 0.04103303],
       [0.8345774 , 0.79479885, 0.59163615, 0.03330879],
       [0.97109986, 0.98794579, 0.29284861, 0.38541722]])

In [78]:
np.random.randn(2,4)

array([[-0.28745247, -0.37094063, -0.05651407, -0.35584737],
       [ 0.40021601,  0.39045845, -1.67834001,  0.92830561]])

In [204]:
np.random.random((3,6))

array([[0.66288554, 0.41630647, 0.09119839, 0.3696542 , 0.49260855,
        0.31407671],
       [0.40301254, 0.30470202, 0.1504751 , 0.45479232, 0.30607221,
        0.59969796],
       [0.64518251, 0.07558315, 0.6825212 , 0.69236254, 0.74709863,
        0.50243124]])

In [177]:
np.random.rand(3,6)

array([[0.0013719 , 0.55726097, 0.56758363, 0.95515247, 0.06994752,
        0.04770157],
       [0.97234376, 0.22137323, 0.94038281, 0.72735497, 0.10797171,
        0.33120547],
       [0.78729237, 0.20472839, 0.48591325, 0.12431353, 0.57271602,
        0.21540993]])

In [81]:
na = np.random.randn(2,8)

In [82]:
na.shape

(2, 8)

In [84]:
nna = na.reshape((2,4,2))

In [86]:
nna.shape

(2, 4, 2)

In [94]:
na = np.arange(1,13).reshape((3,4))

In [95]:
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
na.reshape((3,2,-1))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [102]:
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
na.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
na[-1]

array([ 9, 10, 11, 12])

In [105]:
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
na = np.arange(1,101).reshape((10,10))

In [107]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [115]:
na[:,1:6]

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56],
       [62, 63, 64, 65, 66],
       [72, 73, 74, 75, 76],
       [82, 83, 84, 85, 86],
       [92, 93, 94, 95, 96]])

In [149]:
na[3:7] = np.arange(100,140).reshape((4,10))

In [150]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [151]:
newarr = na[3:7]

In [152]:
newarr

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]])

In [153]:
newarr[0] = np.arange(1,11)

In [154]:
newarr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]])

In [155]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [156]:
newarr2 = na[3:7].copy()

In [157]:
newarr2[0] = np.arange(1001,1011)

In [158]:
newarr2

array([[1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
       [ 110,  111,  112,  113,  114,  115,  116,  117,  118,  119],
       [ 120,  121,  122,  123,  124,  125,  126,  127,  128,  129],
       [ 130,  131,  132,  133,  134,  135,  136,  137,  138,  139]])

In [159]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [160]:
np.shares_memory(na,newarr)

True

In [161]:
np.shares_memory(na,newarr2)

False

In [162]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [172]:
l1 = [1,2,3,4]
l1

[1, 2, 3, 4]

In [173]:
type(l1)

list

In [198]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [201]:
np.random.choice(a,size=(2,3),replace=True,p = [0.2,0.5,0,0,0,0,0,0,0,0.3])

array([[11, 19, 11],
       [10, 10, 19]])

In [225]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [226]:
np.random.seed(1)
np.random.shuffle(a)

In [227]:
a

array([12, 19, 16, 14, 10, 13, 11, 17, 18, 15])

In [231]:
l = [[1,2,3],[4,5]]
a = np.array(l,dtype='object')
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [232]:
a.shape

(2,)

In [236]:
a = np.array([10,20,30,40,50,60])
b = np.array([1,2,3,4,5,6])

In [237]:
a.reshape((2,3))+5

array([[15, 25, 35],
       [45, 55, 65]])

In [238]:
a - 5

array([ 5, 15, 25, 35, 45, 55])

In [239]:
a * 5

array([ 50, 100, 150, 200, 250, 300])

In [240]:
a / 5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [241]:
a // 5

array([ 2,  4,  6,  8, 10, 12])

In [242]:
a % 15

array([10,  5,  0, 10,  5,  0])

In [243]:
a ** 2

array([ 100,  400,  900, 1600, 2500, 3600])

In [244]:
a*10+5

array([105, 205, 305, 405, 505, 605])

In [255]:
a >= 30

array([False, False,  True,  True,  True,  True])

In [254]:
a == 30

array([False, False,  True, False, False, False])

In [260]:
a = np.array([10,20,30,40,50,60])
b = np.array([1,2,3,4,5,6])

In [264]:
a * b #If size is not same we get shape mismatch error

array([ 10,  40,  90, 160, 250, 360])

In [265]:
np.add(a,b)

array([11, 22, 33, 44, 55, 66])

In [266]:
np.subtract(a,b)

array([ 9, 18, 27, 36, 45, 54])

In [267]:
np.multiply(a,b)

array([ 10,  40,  90, 160, 250, 360])

In [268]:
np.divide(a,b)

array([10., 10., 10., 10., 10., 10.])

In [280]:
~(a==b)

array([ True,  True,  True,  True,  True,  True])

In [281]:
a >= 30

array([False, False,  True,  True,  True,  True])

In [283]:
a[[3,1,2]]

array([40, 20, 30])

In [302]:
a = np.arange(10,30).reshape((4,5))

In [303]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [312]:
a[[3,1,0],[3,2,1]] #Gets indexed elements

array([28, 17, 11])

In [313]:
a[[0,2,3]][:,[1,2,3]]

array([[11, 12, 13],
       [21, 22, 23],
       [26, 27, 28]])

In [315]:
a[[True,False,False,True]]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [316]:
a = np.arange(10,20)

In [317]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [320]:
a[a%2 == 0] #Filtering 

array([10, 12, 14, 16, 18])

In [325]:
np.where(a%2 == 0,np.arange(10,20),np.arange(30,40))

array([10, 31, 12, 33, 14, 35, 16, 37, 18, 39])

In [331]:
arr = np.random.random((5,2))
arr[arr > 0.1]

array([0.61393832, 0.95653566, 0.26097898, 0.23101542, 0.53344849,
       0.94993814, 0.49305959, 0.54060051, 0.7654851 ])

In [334]:
np.where(a >= 15)

(array([5, 6, 7, 8, 9]),)

- Basic reductions: sum, min, max, any, all
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate

In [337]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [338]:
np.sum(a)

np.int64(145)

In [339]:
np.max(a)

np.int64(19)

In [340]:
l1 = [1,2,3,4,5]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]]

In [341]:
n1 = np.array(l1,dtype = 'f')
n2 = np.array(l2)
n3 = np.array(l3)

In [344]:
np.sum(n2,axis=0)

array([ 9, 12])

In [345]:
np.sum(n2,axis=1)

array([ 3,  7, 11])

In [347]:
np.sum(n3,axis = 0)

array([[11, 22],
       [33, 44],
       [55, 66]])

In [348]:
np.sum(n3,axis = 1)

array([[  9,  12],
       [ 90, 120]])

In [349]:
np.sum(n3,axis = 2)

array([[  3,   7,  11],
       [ 30,  70, 110]])

In [352]:
np.max(n3,axis = 2)

array([[ 2,  4,  6],
       [20, 40, 60]])

In [355]:
np.mean(n3,axis = 2)

array([[ 1.5,  3.5,  5.5],
       [15. , 35. , 55. ]])

In [357]:
a = np.arange(5)+5

In [358]:
a

array([5, 6, 7, 8, 9])

In [361]:
np.average(a,weights=[2,1,1,1,4])

np.float64(7.444444444444445)

In [373]:
np.sqrt(np.sum((a-np.mean(a))**2)/a.shape[0])

np.float64(1.4142135623730951)

In [374]:
np.std(a)

np.float64(1.4142135623730951)

In [375]:
np.var(a)

np.float64(2.0)

In [386]:
a = np.array([[1],[2]])
b = np.array([4,5,6])

In [387]:
a+b

array([[5, 6, 7],
       [6, 7, 8]])

In [403]:
a = np.array([[1,2,3,4,5]])
b = np.array([[10,20,30,40,50]])

In [408]:
np.stack((a,b),axis = 2)

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30],
        [ 4, 40],
        [ 5, 50]]])

In [405]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50]])

In [406]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [409]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [410]:
a*b

array([[ 5, 12],
       [21, 32]])

In [411]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [412]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [413]:
a@b

array([[19, 22],
       [43, 50]])

In [414]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [415]:
a.T

array([[1, 3],
       [2, 4]])

In [417]:
data = np.loadtxt('populations.txt')

In [419]:
data.shape

(21, 4)

In [426]:
data[np.argmax(data,axis=0),0]

array([1920., 1903., 1904., 1900.])

In [427]:
data[np.argmin(data,axis=0),0]

array([1900., 1917., 1900., 1916.])

In [432]:
data[data[:,1] == np.max(data,axis = 0)[1]][0][0]

np.float64(1903.0)

In [434]:
data = np.loadtxt("populations.txt")
col = ["hare","lynx","carrot"]
for i in data:
    print(i[0] ,"-->", col[np.argmax(i[1:4])])

1900.0 --> carrot
1901.0 --> carrot
1902.0 --> hare
1903.0 --> hare
1904.0 --> lynx
1905.0 --> lynx
1906.0 --> carrot
1907.0 --> carrot
1908.0 --> carrot
1909.0 --> carrot
1910.0 --> carrot
1911.0 --> carrot
1912.0 --> hare
1913.0 --> hare
1914.0 --> hare
1915.0 --> lynx
1916.0 --> carrot
1917.0 --> carrot
1918.0 --> carrot
1919.0 --> carrot
1920.0 --> carrot


In [436]:
data = np.loadtxt("populations.txt")
col = ["hare","lynx","carrot"]
maxVI = np.argmax(data[:,1:],axis = 1)
for i in range(data.shape[0]):
    print(data[i][0],'-->',col[maxVI[i]])

1900.0 --> carrot
1901.0 --> carrot
1902.0 --> hare
1903.0 --> hare
1904.0 --> lynx
1905.0 --> lynx
1906.0 --> carrot
1907.0 --> carrot
1908.0 --> carrot
1909.0 --> carrot
1910.0 --> carrot
1911.0 --> carrot
1912.0 --> hare
1913.0 --> hare
1914.0 --> hare
1915.0 --> lynx
1916.0 --> carrot
1917.0 --> carrot
1918.0 --> carrot
1919.0 --> carrot
1920.0 --> carrot


In [2]:
l1 = [1,2,3]
l2 = [[1,2,3],[4,5,6],[7,8,9]]
l3 = [[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]]

In [3]:
n3 = np.array(l3)
n3.shape

(2, 3, 3)