# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- more creation methods: arange, linespace, ones, zeros, eye, diag
- random numbers: np.random.rand
- reshape: -1 for unknown
- data types: b,i,u,f,c,m,M,O,S,u,V
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting

In [5]:
import numpy as np

In [4]:
# !pip install numpy

In [6]:
l1 = [1,2,3,4,5]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]]

In [37]:
n1 = np.array(l1,dtype = 'f')
n2 = np.array(l2)
n3 = np.array(l3)

In [38]:
n1

array([1., 2., 3., 4., 5.], dtype=float32)

In [9]:
n2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
n3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [11]:
type(n1)

numpy.ndarray

In [12]:
n1.shape

(5,)

In [13]:
n2.shape

(3, 2)

In [14]:
n3.shape

(2, 3, 2)

In [15]:
n3.ndim

3

In [16]:
n3[0,1,0]

np.int64(3)

In [17]:
n1[2]

np.int64(3)

In [20]:
n2[1]

array([3, 4])

In [22]:
n3[1,2]

array([50, 60])

In [28]:
for i in l3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
10
20
30
40
50
60


In [29]:
for ele in np.nditer(n3):
    print(ele)

1
2
3
4
5
6
10
20
30
40
50
60


In [33]:
for ind,ele in np.ndenumerate(n3):
    print(ind,'-->',ele)

(0, 0, 0) --> 1
(0, 0, 1) --> 2
(0, 1, 0) --> 3
(0, 1, 1) --> 4
(0, 2, 0) --> 5
(0, 2, 1) --> 6
(1, 0, 0) --> 10
(1, 0, 1) --> 20
(1, 1, 0) --> 30
(1, 1, 1) --> 40
(1, 2, 0) --> 50
(1, 2, 1) --> 60


more creation methods: arange, linspace, ones, zeros, eye, diag

In [55]:
na = np.arange(1,21,2,dtype='int16')

In [56]:
na.dtype

dtype('int16')

In [57]:
na

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int16)

In [61]:
np.linspace(100,200,5)

array([100., 125., 150., 175., 200.])

In [65]:
np.ones((2,3,2),dtype='i')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [66]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [72]:
np.eye(4,dtype = 'i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [73]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [79]:
(np.random.rand(2,3,2)*100)+100

array([[[102.39230654, 126.86058755],
        [140.7357499 , 105.22117261],
        [193.74621991, 127.04319102]],

       [[168.29996811, 138.81254712],
        [131.42716978, 129.6578381 ],
        [179.72505653, 104.59848425]]])

In [76]:
np.random.randint(1000,2000,size=(2,4))

array([[1111, 1383, 1126, 1653],
       [1759, 1913, 1957, 1990]], dtype=int32)

In [77]:
np.random.random((3,4))

array([[0.67823875, 0.35521759, 0.00843601, 0.04103303],
       [0.8345774 , 0.79479885, 0.59163615, 0.03330879],
       [0.97109986, 0.98794579, 0.29284861, 0.38541722]])

In [78]:
np.random.randn(2,4)

array([[-0.28745247, -0.37094063, -0.05651407, -0.35584737],
       [ 0.40021601,  0.39045845, -1.67834001,  0.92830561]])

In [81]:
na = np.random.randn(2,8)

In [82]:
na.shape

(2, 8)

In [84]:
nna = na.reshape((2,4,2))

In [86]:
nna.shape

(2, 4, 2)

In [94]:
na = np.arange(1,13).reshape((3,4))

In [95]:
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
na.reshape((3,2,-1))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [102]:
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
na.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
na[-1]

array([ 9, 10, 11, 12])

In [105]:
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
na = np.arange(1,101).reshape((10,10))

In [107]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [115]:
na[:,1:6]

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56],
       [62, 63, 64, 65, 66],
       [72, 73, 74, 75, 76],
       [82, 83, 84, 85, 86],
       [92, 93, 94, 95, 96]])

In [149]:
na[3:7] = np.arange(100,140).reshape((4,10))

In [150]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [151]:
newarr = na[3:7]

In [152]:
newarr

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]])

In [153]:
newarr[0] = np.arange(1,11)

In [154]:
newarr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]])

In [155]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [156]:
newarr2 = na[3:7].copy()

In [157]:
newarr2[0] = np.arange(1001,1011)

In [158]:
newarr2

array([[1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
       [ 110,  111,  112,  113,  114,  115,  116,  117,  118,  119],
       [ 120,  121,  122,  123,  124,  125,  126,  127,  128,  129],
       [ 130,  131,  132,  133,  134,  135,  136,  137,  138,  139]])

In [159]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [160]:
np.shares_memory(na,newarr)

True

In [161]:
np.shares_memory(na,newarr2)

False

In [162]:
na

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])